Main/urls.py
from django.urls import path
from .views import LandingPage, AboutUs, Map
from . import views

app_name = 'main'

urlpatterns = [
    path('',LandingPage.as_view(),name='index'),
    path('about',AboutUs.as_view(),name='about'),
    path('menu',Map.as_view(),name='menu'),
    path('coordinates/',views.get_coordinates,name='coordinates'),
    path('health/',views.health,name='health'),
]

SafetyNxt/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from Main import urls as main_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(main_urls,namespace='main')),
    path('accounts/',include('allauth.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base.html' %}

{% block links %}
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="/static/css/about.css">
    <link rel="stylesheet" href="/static/css/base-style.css">

{% endblock %}

{% block title %} About Us {% endblock %}

{% block content %}

<!-- Add all the About Us code here-->
    <section class="about about-1">
        <div class="container">
            <h2>About Us</h2>
            <div class="flex-row">
                <div class="left">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt, odio voluptatum? Nihil nemo, delectus, magnam dolorem velit veritatis ullam corporis error natus cupiditate animi architecto inventore esse dolor nesciunt illo.</p>
                    <div class="flex-row">
                        <i class="fa-solid fa-bullhorn" style="color: #2288ff;"></i>
                        <div class="info">
                            <h4>Title #1</h4>
                            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum dolores nemo sapiente ratione deleniti magnam corporis commodi? Exercitationem quaerat pariatur consequuntur? Ducimus exercitationem pariatur fuga corrupti neque totam deleniti tenetur.</p>
                        </div>
                    </div>

                    <div class="flex-row">
                        <i class="fa-solid fa-bullhorn" style="color: #2288ff;"></i>
                        <div class="info">
                            <h4>Title #1</h4>
                            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum dolores nemo sapiente ratione deleniti magnam corporis commodi? Exercitationem quaerat pariatur consequuntur? Ducimus exercitationem pariatur fuga corrupti neque totam deleniti tenetur.</p>
                        </div>
                    </div>

                    <div class="flex-row">
                        <i class="fa-solid fa-bullhorn" style="color: #2288ff;"></i>
                        <div class="info">
                            <h4>Title #1</h4>
                            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum dolores nemo sapiente ratione deleniti magnam corporis commodi? Exercitationem quaerat pariatur consequuntur? Ducimus exercitationem pariatur fuga corrupti neque totam deleniti tenetur.</p>
                        </div>
                    </div>
                </div>
                <div class="right">
                    <img src="/static/img/about/about-img.svg" alt="" />
                </div>
            </div>
        </div>
    </section>


    <section class="about about-2">
        <div class="container flex-row">
            <div class="left">
                <img src="/static/img/about/about-extra-1.svg" alt="">
            </div>
            <div class="right">
                <h3>About Us Secondary Content</h3>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati, nostrum. Fuga vitae ipsum nobis id animi minima ad vero recusandae quo labore eveniet dolores nesciunt officia, deleniti, aliquam natus nihil?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae repellat esse ex vitae! Repellendus vel sint esse, aut minima laborum, illo eum consequatur necessitatibus sunt reprehenderit dicta quasi facilis molestiae.</p>
            </div>
        </div>
    </section>


    <section class="about about-3">
        <div class="container flex-row">
            <div class="left">
                <h3>About Us Secondary Content</h3>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati, nostrum. Fuga vitae ipsum nobis id animi minima ad vero recusandae quo labore eveniet dolores nesciunt officia, deleniti, aliquam natus nihil?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae repellat esse ex vitae! Repellendus vel sint esse, aut minima laborum, illo eum consequatur necessitatibus sunt reprehenderit dicta quasi facilis molestiae.</p>
            </div>

            <div class="right">
                <img src="/static/img/about/about-extra-2.svg" alt="">
            </div>
        </div>
    </section>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Box Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
<!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">-->

    {% block links %}
        <link rel="stylesheet" href="/static/css/base-style.css">
    {% endblock %}
    <title>{% block title %} SafetyNxt {% endblock %}</title>
</head>
<body>

    <!--Navbar-->
    <header>
        {% if messages %}
            {% for message in messages %}
                <div class="bg-success text-center text-white py-4">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        <div class="nav container">

            <!-- Logo  -->
            <a href="/" class="logo"><img src="/static/img/home/logo.png" alt="">SafetyNXT</a>

            <!-- menu Icon -->
            <input type="checkbox" name="" id="menu">
            <label for="menu">
                <i class='bx bx-menu' id="menu-icon"></i>
            </label>

            <!-- Nav List -->
            <ul class="navbar">
                <li><a href="/">Home</a></li>
                <li><a href="/#services">Services</a></li>
                <li><a href="/#contact">Contact</a></li>
                <li><a href="/#testimonial">Review</a></li>
                <li><a href="{% url 'main:about' %}">About</a></li>
            </ul>

            {% if user.is_authenticated %}
            <!-- Log In Btn -->
            <a href="{% url 'account_logout' %}" class="btn">Logout</a>

            {% else %}
            <a href="{% url 'account_login' %}" class="btn">LogIn</a>

            {% endif %}

        </div>
    </header>

    {% block content %} {% endblock %}
<div class="main">

    <footer>

        <div class="row">
            <div class="col">
               <ul>
                <li> <div class="logo"><a href="#">SafetyNXT</a></div></li>
                <li><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. vitae laboriosam alias iusto fuga? Magnam, illo.</p></li>
               </ul>

            </div>
            <div class="col">
                <ul>
                    <li>+1 23 (555) 5858</li>
                    <li>example@gmail.com</li>
                    <li>Pune,India</li>
                </ul>
            </div>
            <div class="col">
                <ul>
                    <li><a href="#home">Home</a></li>
                    <li><a href="{% url 'main:about' %}}">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                    <li><a href="#services">Services</a></li>
                    <li><a href="#team">Team</a></li>
                </ul>
            </div>
            <div class="col">
                <ul class="social">
                    <li>
                        <i class="fa-brands fa-facebook-f"></i>
                    </li>
                    <li>
                        <i class="fa-brands fa-instagram"></i>
                    </li>
                    <li>
                        <i class="fa-brands fa-linkedin-in"></i>
                    </li>
                    <li>
                        <i class="fa-brands fa-x-twitter"></i>
                    </li>

                </ul>
            </div>
        </div>
        <p>&copy; 2023|| All Rights Reserved by SafetyNXT</p>
      </footer>
    </div>
</body>

<script src="/static/js/script.js"></script>
<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>-->
{% block js %} {% endblock %}
</html>

templates/menu.html
<!DOCTYPE html>
<html>

<head>
  <title>Geolocation</title>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css" />
  <link rel="stylesheet" href="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.css" />
  <link rel="stylesheet" href="https://unpkg.com/leaflet-contextmenu@latest/dist/leaflet.contextmenu.min.css" />
  <link rel="stylesheet" href="static/css/menu.css">
    <!-- Include Awesomplete CSS and JS -->
  <link rel="stylesheet" href="https://unpkg.com/awesomplete/awesomplete.css" />
  <script src="https://unpkg.com/awesomplete/awesomplete.min.js" defer></script>

  <style>
    #map {
      height: 800px;
    }
  </style>

</head>

<body>


  <div id="directions-box">
    <div id="directions-title">Driving Directions</div>

    <div class="container">
      <!-- Input fields for starting point and destination -->
      <div class="input-box">
        <img class="icon-left" src="/static/img/start location.png" />
        <div class="bg-bar"></div>
        <img class="icon-right" src="/static/img/search.png" />
        <input type="text" id="from" class="text-box" list="location-suggestions" placeholder="Choose starting point" />
        <datalist id="location-suggestions"></datalist>
      </div>

      <div class="destination-box">
        <img class="icon-left" src="/static/img/destination.png" />
        <div class="bg-bar"></div>
        <img class="icon-right" src="/static/img/search.png" />
        <input type="text" id="to" list="location-suggestions" class="text-box" placeholder="Choose destination" />
      </div>

      <!-- Rotate Icon -->
      <img class="rotate-icon" src="/static/img/dot.png" />

      <!-- Additional Icon -->
      <img class="additional-icon" src="/static/img/switch.png" onclick="reverseInputs()" />

      <!-- Find Route Box -->
      <div class="find-route-box">
        <div class="background-bar"></div>
        <!-- Button to trigger findRoute function -->
        <button class="find-route-text" onclick="getRoute()">
          Start Monitoring
        </button>
      </div>
    </div>
  </div>

  <label>
    <input type="checkbox" />
    <div class="toggle">
      <span class="top_line common"></span>
      <span class="middle_line common"></span>
      <span class="bottom_line common"></span>
    </div>
    <div class="slide">
      <div class="header">
        <div class="title">Select Service</div>
        <img class="icon1" src="static/img/service.png" />
      </div>

      <ul>
        <li>
          <div class="service-block">
            <div class="service-title">Traffic Monitoring</div>
            <img class="icon" src="/static/img/traffic.png" />
            <!-- toggle button -->
            <label class="toggle_box">
              <input type="checkbox" id="trafficCheckbox" onchange="updateMapMarkers()" checked />
              <div class="circle"></div>
            </label>
          </div>
        </li>

        <li>
          <div class="service-block">
            <div class="service-title">Accident Detection</div>
            <img class="icon" src="/static/img/accident.png" />
            <label class="toggle_box">
              <input type="checkbox" id="accidentCheckbox" onchange="updateMapMarkers()" checked />
              <div class="circle"></div>
            </label>
          </div>
        </li>

        <li>
          <div class="service-block">
            <div class="service-title">Pothole Identification</div>
            <img class="icon" src="/static/img/pothole.png" />
            <label class="toggle_box">
              <input type="checkbox" id="potholeCheckbox" onchange="updateMapMarkers()" checked />
              <div class="circle"></div>
            </label>
          </div>
        </li>
      </ul>
    </div>
  </label>

  <a href="{% url 'account_login' %}">
    <button id="logout-btn" class="logout-button">Cancel</button>
  </a>

  <a href="/" class="logo"><img src="/static/img/home/logo.png" alt="">SafetyNXT</a>

  <div id="map"></div>

  <div id="steps"></div>

  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"></script>
  <script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>
  <script src="https://unpkg.com/leaflet-control-geocoder@latest/dist/Control.Geocoder.js"></script>
  <script src="https://unpkg.com/leaflet-contextmenu@latest/dist/leaflet.contextmenu.min.js"></script>

  <script src="static/js/map1.js"></script>
  <script>
    // toggle--------------------------------------------------------------------------------------------------------------

    // Toggle Background box selection
    let background_boxes = document.querySelectorAll(".background_box");

    // Checkboxes selection
    let toggleBoxes = document.querySelectorAll(".toggle_box");
    let trafficToggleBox = document.getElementById("trafficCheckbox");
    let potholeToggleBox = document.getElementById("potholeCheckbox");
    let accidentToggleBox = document.getElementById("accidentCheckbox");

    let circles = document.querySelectorAll(".circle");

    // Add click event listeners to each toggle box
    toggleBoxes.forEach(function (toggleBox, index) {
      toggleBox.onclick = function () {
        // Toggle the checkbox
        let checkbox = toggleBox.querySelector("input[type='checkbox']");
        checkbox.checked = !checkbox.checked;

        // Move the circle based on the checkbox state
        let circle = circles[index];
        if (checkbox.checked) {
          circle.style.transform = "translateX(34px)";
          circle.style.backgroundColor = "#fff"; // Set "on" color
        } else {
          circle.style.transform = "translateX(0px)";
          circle.style.backgroundColor = "#000"; // Set "off" color
        }
      };
    });

    function updateMapMarkers() {
    var trafficChecked = document.getElementById('trafficCheckbox').checked;
    var accidentChecked = document.getElementById('accidentCheckbox').checked;
    var potholeChecked = document.getElementById('potholeCheckbox').checked;

    // Add or remove traffic markers based on checkbox state
    if (trafficChecked) {
        trafficMarkers.forEach(marker => marker.addTo(map));
    } else {
        trafficMarkers.forEach(marker => map.removeLayer(marker));
    }

    // Add or remove accident markers based on checkbox state
    if (accidentChecked) {
        accidentMarkers.forEach(marker => marker.addTo(map));
    } else {
        accidentMarkers.forEach(marker => map.removeLayer(marker));
    }

    // Add or remove pothole markers based on checkbox state
    if (potholeChecked) {
        potholeMarkers.forEach(marker => marker.addTo(map));
    } else {
        potholeMarkers.forEach(marker => map.removeLayer(marker));
    }
    }
  </script>

</body>

</html>